// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClNUlafLIuCRmMUNYHkHG4dVSZicDXV4s',
    appId: '1:450875008009:web:bdde0cc37900592a7c84d8',
    messagingSenderId: '450875008009',
    projectId: 'bookmarkpoc',
    authDomain: 'bookmarkpoc.firebaseapp.com',
    databaseURL: 'https://bookmarkpoc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookmarkpoc.firebasestorage.app',
    measurementId: 'G-PRBCZTV0BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9lTj_uYjSyn2eK-kiLZ5aud4DaR0ZllU',
    appId: '1:450875008009:android:36472a795b5e700e7c84d8',
    messagingSenderId: '450875008009',
    projectId: 'bookmarkpoc',
    databaseURL: 'https://bookmarkpoc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookmarkpoc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD65bv3Lg9a8x5TWE0CRY5F3UNPbZTTiQg',
    appId: '1:450875008009:ios:0bae1212d8d9da987c84d8',
    messagingSenderId: '450875008009',
    projectId: 'bookmarkpoc',
    databaseURL: 'https://bookmarkpoc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookmarkpoc.firebasestorage.app',
    iosBundleId: 'com.example.bookmarkPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD65bv3Lg9a8x5TWE0CRY5F3UNPbZTTiQg',
    appId: '1:450875008009:ios:0bae1212d8d9da987c84d8',
    messagingSenderId: '450875008009',
    projectId: 'bookmarkpoc',
    databaseURL: 'https://bookmarkpoc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookmarkpoc.firebasestorage.app',
    iosBundleId: 'com.example.bookmarkPoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClNUlafLIuCRmMUNYHkHG4dVSZicDXV4s',
    appId: '1:450875008009:web:0714c1858fae73577c84d8',
    messagingSenderId: '450875008009',
    projectId: 'bookmarkpoc',
    authDomain: 'bookmarkpoc.firebaseapp.com',
    databaseURL: 'https://bookmarkpoc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookmarkpoc.firebasestorage.app',
    measurementId: 'G-S7L8VD8DBG',
  );
}